services:
  backend:
    build:
      context: ./src/backend
    container_name: financial-security-system-backend
    volumes:
      - ./src:/src
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
