name: Run Python Tests

on:
  push:
    paths:
      - '**.py'
    branches:
      - main
  pull_request:
    paths:
      - '**.py'
  # RUN manually
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup pyenv
        uses: gabrielfalcao/pyenv-action@v18
        with:
          default: 3.13.2
          versions: 3.13.2, 3.13.2
          command: pyenv versions

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache virtual environments
        uses: actions/cache@v3
        with:
          path: |
            **/.venv
          key: ${{ runner.os }}-venv-py${{ runner.python-version }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-py${{ runner.python-version }}-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Run the sync_venvs script to set up all virtual environments
          chmod +x ./scripts/sync_venvs.sh
          ./scripts/sync_venvs.sh

      - name: Run tests
        run: |
          # Make the script executable
          chmod +x ./scripts/run_all_tests.sh
          # Run tests with specified parameters
          ./scripts/run_all_tests.sh --tb=short --disable-warnings --maxfail=1
