name: Run Python Tests

on:
  push:
    paths:
      - '**.py'
    branches:
      - main
  pull_request:
    paths:
      - '**.py'
  # RUN manually
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup pyenv
        uses: gabrielfalcao/pyenv-action@v18
        with:
          default: 3.13.1
          versions: 3.13.1, 3.12.8
          command: pip install -U pip

      - name: Cache virtual environments
        uses: actions/cache@v3
        with:
          path: |
            **/.venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements.txt', '**/.pythonversion') }}
          restore-keys: |
            ${{ runner.os }}-venv-

      - name: Install dependencies
        run: |
          # Make the script executable
          chmod +x ./scripts/sync_venvs.sh
          # Run the sync_venvs script to set up all virtual environments
          ./scripts/sync_venvs.sh

      - name: Run tests
        run: |
          # Make the script executable
          chmod +x ./scripts/run_all_tests.sh
          # Run tests with specified parameters
          ./scripts/run_all_tests.sh --tb=short --disable-warnings --maxfail=1
