name: Run Python Tests

on:
  push:
    paths:
      - '**.py'
    branches:
      - main
  pull_request:
    paths:
      - '**.py'
  # RUN manually
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install required build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            make build-essential libssl-dev zlib1g-dev \
            libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm \
            libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev \
            liblzma-dev

      - name: setup pyenv
        uses: gabrielfalcao/pyenv-action@v18
        with:
          default: 3.13.1
          versions: 3.12.8, 3.10.0
          command: pip install -U pip

      - name: Install dependencies
        run: |
          # Make the script executable
          chmod +x ./scripts/sync_venvs.sh
          # Run the sync_venvs script to set up all virtual environments
          ./scripts/sync_venvs.sh

      - name: Run tests
        run: |
          # Make the script executable
          chmod +x ./scripts/run_all_tests.sh
          # Run tests with specified parameters
          ./scripts/run_all_tests.sh --tb=short --disable-warnings --maxfail=1
